[project]
name = "smart_data"
repository = "https://github.com/pkoscielny/smart_data"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pytest",
    "pytest-cov",
]
build-backend = "setuptools.build_meta"
